// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

import "react";

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "arcgis-map": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement> & {
        "item-id"?: string;
        basemap?: string;
        center?: string;
        zoom?: string | number;
      }, HTMLElement>;
      "arcgis-zoom": React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement> & {
        slot?: string;
        position?: string;
      }, HTMLElement>;
    }
  }
}
