#!/usr/bin/env python3
"""Emit app/src/ntaToCanonicalNeighborhood.json from NTA → canonical areaName rules."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEO = ROOT / "src" / "nyc_neighborhoods.json"
OUT = ROOT / "src" / "ntaToCanonicalNeighborhood.json"

# Canonical names from rent model (must match DB areaName / neighborhood column)
CANONICAL = {
    "All Downtown",
    "All Midtown",
    "All Upper East Side",
    "All Upper Manhattan",
    "All Upper West Side",
    "Astoria",
    "Battery Park City",
    "Bay Ridge",
    "Bayside",
    "Bedford-Stuyvesant",
    "Bensonhurst",
    "Boerum Hill",
    "Borough Park",
    "Briarwood",
    "Brighton Beach",
    "Bronx",
    "Brooklyn",
    "Brooklyn Heights",
    "Brownsville",
    "Bushwick",
    "Carroll Gardens",
    "Central Harlem",
    "Central Park South",
    "Central Queens",
    "Chelsea",
    "Chinatown",
    "Clinton Hill",
    "Cobble Hill",
    "Columbia St Waterfront District",
    "Concourse",
    "Coney Island",
    "Corona",
    "Crown Heights",
    "DUMBO",
    "Ditmas Park",
    "Downtown Brooklyn",
    "Dyker Heights",
    "East Brooklyn",
    "East Flatbush",
    "East Harlem",
    "East New York",
    "East Village",
    "Elmhurst",
    "Financial District",
    "Flatbush",
    "Flatiron",
    "Flushing",
    "Forest Hills",
    "Fort Greene",
    "Glendale",
    "Gowanus",
    "Gramercy Park",
    "Gravesend",
    "Greenpoint",
    "Greenwich Village",
    "Greenwood",
    "Hamilton Heights",
    "Inwood",
    "Jackson Heights",
    "Kensington",
    "Kew Gardens",
    "Kew Gardens Hills",
    "Kingsbridge",
    "Little Italy",
    "Long Island City",
    "Lower East Side",
    "Manhattan",
    "Midtown",
    "Midtown East",
    "Midtown South",
    "Midtown West",
    "Midwood",
    "Morningside Heights",
    "Mott Haven",
    "NYC",
    "Nolita",
    "North Brooklyn",
    "Northeast Queens",
    "Northwest Brooklyn",
    "Northwest Queens",
    "Park Slope",
    "Prospect Heights",
    "Prospect Lefferts Gardens",
    "Prospect Park",
    "Prospect Park South",
    "Queens",
    "Red Hook",
    "Rego Park",
    "Ridgewood",
    "Riverdale",
    "Rockaway All",
    "Roosevelt Island",
    "Sheepshead Bay",
    "Soho",
    "South Brooklyn",
    "South Queens",
    "Staten Island",
    "Stuyvesant Town/PCV",
    "Sunnyside",
    "Sunset Park",
    "The Rockaways",
    "Tribeca",
    "University Heights",
    "Upper East Side",
    "Upper West Side",
    "Washington Heights",
    "West Harlem",
    "West Village",
    "Williamsburg",
    "Windsor Terrace",
    "Woodside",
}

# Every NTAName in GeoJSON → one canonical label
NTA_MAP: dict[str, str] = {
    "Allerton": "Kingsbridge",
    "Alley Pond Park": "Northeast Queens",
    "Annadale-Huguenot-Prince's Bay-Woodrow": "Staten Island",
    "Arden Heights-Rossville": "Staten Island",
    "Astoria (Central)": "Astoria",
    "Astoria (East)-Woodside (North)": "Astoria",
    "Astoria (North)-Ditmars-Steinway": "Astoria",
    "Astoria Park": "Astoria",
    "Auburndale": "Bayside",
    "Baisley Park": "South Queens",
    "Barren Island-Floyd Bennett Field": "East Brooklyn",
    "Bath Beach": "Bensonhurst",
    "Bay Ridge": "Bay Ridge",
    "Bay Terrace-Clearview": "Bayside",
    "Bayside": "Bayside",
    "Bedford Park": "Kingsbridge",
    "Bedford-Stuyvesant (East)": "Bedford-Stuyvesant",
    "Bedford-Stuyvesant (West)": "Bedford-Stuyvesant",
    "Bellerose": "Central Queens",
    "Belmont": "Concourse",
    "Bensonhurst": "Bensonhurst",
    "Borough Park": "Borough Park",
    "Breezy Point-Belle Harbor-Rockaway Park-Broad Channel": "Rockaway All",
    "Brighton Beach": "Brighton Beach",
    "Bronx Park": "Bronx",
    "Brooklyn Heights": "Brooklyn Heights",
    "Brooklyn Navy Yard": "North Brooklyn",
    "Brownsville": "Brownsville",
    "Bushwick (East)": "Bushwick",
    "Bushwick (West)": "Bushwick",
    "Calvary & Mount Zion Cemeteries": "Queens",
    "Calvert Vaux Park": "South Brooklyn",
    "Cambria Heights": "South Queens",
    "Canarsie": "East Brooklyn",
    "Canarsie Park & Pier": "East Brooklyn",
    "Carroll Gardens-Cobble Hill-Gowanus-Red Hook": "Carroll Gardens",
    "Castle Hill-Unionport": "Bronx",
    "Central Park": "Central Park South",
    "Chelsea-Hudson Yards": "Chelsea",
    "Chinatown-Two Bridges": "Chinatown",
    "Claremont Park": "Concourse",
    "Claremont Village-Claremont (East)": "Concourse",
    "Clinton Hill": "Clinton Hill",
    "Co-op City": "Bronx",
    "College Point": "Northeast Queens",
    "Concourse-Concourse Village": "Concourse",
    "Coney Island-Sea Gate": "Coney Island",
    "Corona": "Corona",
    "Crotona Park": "Bronx",
    "Crotona Park East": "Bronx",
    "Crown Heights (North)": "Crown Heights",
    "Crown Heights (South)": "Crown Heights",
    "Cunningham Park": "Queens",
    "Cypress Hills": "East New York",
    "Douglaston-Little Neck": "Northeast Queens",
    "Downtown Brooklyn-DUMBO-Boerum Hill": "Downtown Brooklyn",
    "Dyker Beach Park": "Dyker Heights",
    "Dyker Heights": "Dyker Heights",
    "East Elmhurst": "Elmhurst",
    "East Flatbush-Erasmus": "East Flatbush",
    "East Flatbush-Farragut": "East Flatbush",
    "East Flatbush-Remsen Village": "East Flatbush",
    "East Flatbush-Rugby": "East Flatbush",
    "East Flushing": "Flushing",
    "East Harlem (North)": "East Harlem",
    "East Harlem (South)": "East Harlem",
    "East Midtown-Turtle Bay": "Midtown East",
    "East New York (North)": "East New York",
    "East New York-City Line": "East New York",
    "East New York-New Lots": "East New York",
    "East Village": "East Village",
    "East Williamsburg": "Williamsburg",
    "Eastchester-Edenwald-Baychester": "Bronx",
    "Elmhurst": "Elmhurst",
    "Far Rockaway-Bayswater": "The Rockaways",
    "Ferry Point Park-St. Raymond Cemetery": "Bronx",
    "Financial District-Battery Park City": "Financial District",
    "Flatbush": "Flatbush",
    "Flatbush (West)-Ditmas Park-Parkville": "Ditmas Park",
    "Flatlands": "Flatbush",
    "Flushing Meadows-Corona Park": "Flushing",
    "Flushing-Willets Point": "Flushing",
    "Fordham Heights": "University Heights",
    "Forest Hills": "Forest Hills",
    "Forest Park": "Queens",
    "Fort Greene": "Fort Greene",
    "Fort Hamilton": "Bay Ridge",
    "Fort Totten": "Northeast Queens",
    "Fort Wadsworth": "Staten Island",
    "Fresh Meadows-Utopia": "Central Queens",
    "Freshkills Park (North)": "Staten Island",
    "Freshkills Park (South)": "Staten Island",
    "Glen Oaks-Floral Park-New Hyde Park": "Central Queens",
    "Glendale": "Glendale",
    "Gramercy": "Gramercy Park",
    "Grasmere-Arrochar-South Beach-Dongan Hills": "Staten Island",
    "Gravesend (East)-Homecrest": "Sheepshead Bay",
    "Gravesend (South)": "Gravesend",
    "Gravesend (West)": "Gravesend",
    "Great Kills Park": "Staten Island",
    "Great Kills-Eltingville": "Staten Island",
    "Green-Wood Cemetery": "Greenwood",
    "Greenpoint": "Greenpoint",
    "Greenwich Village": "Greenwich Village",
    "Hamilton Heights-Sugar Hill": "Hamilton Heights",
    "Harlem (North)": "Central Harlem",
    "Harlem (South)": "Central Harlem",
    "Hart Island": "Bronx",
    "Hell's Kitchen": "Midtown West",
    "Highbridge": "Concourse",
    "Highbridge Park": "Washington Heights",
    "Highland Park-Cypress Hills Cemeteries (North)": "East Brooklyn",
    "Highland Park-Cypress Hills Cemeteries (South)": "East Brooklyn",
    "Hoffman & Swinburne Islands": "NYC",
    "Hollis": "South Queens",
    "Holy Cross Cemetery": "Brooklyn",
    "Howard Beach-Lindenwood": "South Queens",
    "Hunts Point": "Mott Haven",
    "Hutchinson Metro Center": "Bronx",
    "Inwood": "Inwood",
    "Inwood Hill Park": "Inwood",
    "Jackson Heights": "Jackson Heights",
    "Jacob Riis Park-Fort Tilden-Breezy Point Tip": "The Rockaways",
    "Jamaica": "Central Queens",
    "Jamaica Bay (East)": "South Queens",
    "Jamaica Bay (West)": "South Queens",
    "Jamaica Estates-Holliswood": "Central Queens",
    "Jamaica Hills-Briarwood": "Briarwood",
    "John F. Kennedy International Airport": "South Queens",
    "Kensington": "Kensington",
    "Kew Gardens": "Kew Gardens",
    "Kew Gardens Hills": "Kew Gardens Hills",
    "Kingsbridge Heights-Van Cortlandt Village": "Kingsbridge",
    "Kingsbridge-Marble Hill": "Kingsbridge",
    "Kissena Park": "Flushing",
    "LaGuardia Airport": "Northwest Queens",
    "Laurelton": "South Queens",
    "Lincoln Terrace Park": "Crown Heights",
    "Long Island City-Hunters Point": "Long Island City",
    "Longwood": "Mott Haven",
    "Lower East Side": "Lower East Side",
    "Madison": "Midtown East",
    "Manhattanville-West Harlem": "West Harlem",
    "Mapleton-Midwood (West)": "Midwood",
    "Marine Park-Mill Basin-Bergen Beach": "East Brooklyn",
    "Marine Park-Plumb Island": "East Brooklyn",
    "Mariner's Harbor-Arlington-Graniteville": "Staten Island",
    "Maspeth": "Northwest Queens",
    "McGuire Fields": "South Brooklyn",
    "Melrose": "Mott Haven",
    "Middle Village": "Northwest Queens",
    "Middle Village Cemetery": "Queens",
    "Midtown South-Flatiron-Union Square": "Flatiron",
    "Midtown-Times Square": "Midtown",
    "Midwood": "Midwood",
    "Miller Field": "Staten Island",
    # GeoJSON lists this NTA under Queens (cemetery parcel); not the Bronx Montefiore NTA.
    "Montefiore Cemetery": "South Queens",
    "Morningside Heights": "Morningside Heights",
    "Morris Park": "Bronx",
    "Morrisania": "Bronx",
    "Mott Haven-Port Morris": "Mott Haven",
    "Mount Eden-Claremont (West)": "Concourse",
    "Mount Hebron & Cedar Grove Cemeteries": "Queens",
    "Mount Hope": "Bronx",
    "Mount Olivet & All Faiths Cemeteries": "Queens",
    "Murray Hill-Broadway Flushing": "Flushing",
    "Murray Hill-Kips Bay": "Midtown East",
    "New Dorp-Midland Beach": "Staten Island",
    "New Springville-Willowbrook-Bulls Head-Travis": "Staten Island",
    "North & South Brother Islands": "NYC",
    "North Corona": "Corona",
    "Norwood": "Kingsbridge",
    "Oakland Gardens-Hollis Hills": "Northeast Queens",
    "Oakwood-Richmondtown": "Staten Island",
    "Ocean Hill": "Bedford-Stuyvesant",
    "Old Astoria-Hallets Point": "Astoria",
    "Ozone Park": "South Queens",
    "Ozone Park (North)": "South Queens",
    "Park Slope": "Park Slope",
    "Parkchester": "Concourse",
    "Pelham Bay Park": "Bronx",
    "Pelham Bay-Country Club-City Island": "Bronx",
    "Pelham Gardens": "Bronx",
    "Pelham Parkway-Van Nest": "Bronx",
    "Pomonok-Electchester-Hillcrest": "Flushing",
    "Port Richmond": "Staten Island",
    "Prospect Heights": "Prospect Heights",
    "Prospect Lefferts Gardens-Wingate": "Prospect Lefferts Gardens",
    "Prospect Park": "Prospect Park",
    "Queens Village": "Central Queens",
    "Queensboro Hill": "Flushing",
    "Queensbridge-Ravenswood-Dutch Kills": "Long Island City",
    "Randall's Island": "NYC",
    "Rego Park": "Rego Park",
    "Richmond Hill": "South Queens",
    "Ridgewood": "Ridgewood",
    "Rikers Island": "NYC",
    "Riverdale-Spuyten Duyvil": "Riverdale",
    "Rockaway Beach-Arverne-Edgemere": "The Rockaways",
    "Rockaway Community Park": "The Rockaways",
    "Rosebank-Shore Acres-Park Hill": "Staten Island",
    "Rosedale": "South Queens",
    "Sheepshead Bay-Manhattan Beach-Gerritsen Beach": "Sheepshead Bay",
    "Shirley Chisholm State Park": "East Brooklyn",
    "Snug Harbor": "Staten Island",
    "SoHo-Little Italy-Hudson Square": "Soho",
    "Soundview Park": "Bronx",
    "Soundview-Bruckner-Bronx River": "Bronx",
    "Soundview-Clason Point": "Bronx",
    "South Jamaica": "South Queens",
    "South Ozone Park": "South Queens",
    "South Richmond Hill": "South Queens",
    "South Williamsburg": "Williamsburg",
    "Spring Creek Park": "East Brooklyn",
    "Spring Creek-Starrett City": "East Brooklyn",
    "Springfield Gardens (North)-Rochdale Village": "South Queens",
    "Springfield Gardens (South)-Brookville": "South Queens",
    "St. Albans": "South Queens",
    "St. George-New Brighton": "Staten Island",
    "St. John Cemetery": "Queens",
    "St. Michael's Cemetery": "Queens",
    "Stuyvesant Town-Peter Cooper Village": "Stuyvesant Town/PCV",
    "Sunnyside": "Sunnyside",
    "Sunnyside Yards (North)": "Long Island City",
    "Sunnyside Yards (South)": "Sunnyside",
    "Sunset Park (Central)": "Sunset Park",
    "Sunset Park (East)-Borough Park (West)": "Sunset Park",
    "Sunset Park (West)": "Sunset Park",
    "The Battery-Governors Island-Ellis Island-Liberty Island": "Financial District",
    "The Evergreens Cemetery": "East Brooklyn",
    "Throgs Neck-Schuylerville": "Bronx",
    "Todt Hill-Emerson Hill-Lighthouse Hill-Manor Heights": "Staten Island",
    "Tompkinsville-Stapleton-Clifton-Fox Hills": "Staten Island",
    "Tottenville-Charleston": "Staten Island",
    "Tremont": "Concourse",
    "Tribeca-Civic Center": "Tribeca",
    "United Nations": "Midtown East",
    "University Heights (North)-Fordham": "University Heights",
    "University Heights (South)-Morris Heights": "University Heights",
    "Upper East Side-Carnegie Hill": "Upper East Side",
    "Upper East Side-Lenox Hill-Roosevelt Island": "Upper East Side",
    "Upper East Side-Yorkville": "Upper East Side",
    "Upper West Side (Central)": "Upper West Side",
    "Upper West Side-Lincoln Square": "Upper West Side",
    "Upper West Side-Manhattan Valley": "Upper West Side",
    "Van Cortlandt Park": "Kingsbridge",
    "Wakefield-Woodlawn": "Kingsbridge",
    "Washington Heights (North)": "Washington Heights",
    "Washington Heights (South)": "Washington Heights",
    "West Farms": "Bronx",
    "West New Brighton-Silver Lake-Grymes Hill": "Staten Island",
    "West Village": "West Village",
    "Westchester Square": "Bronx",
    "Westerleigh-Castleton Corners": "Staten Island",
    "Whitestone-Beechhurst": "Northeast Queens",
    "Williamsbridge-Olinville": "Bronx",
    "Williamsburg": "Williamsburg",
    "Windsor Terrace-South Slope": "Windsor Terrace",
    "Woodhaven": "South Queens",
    "Woodlawn Cemetery": "Kingsbridge",
    "Woodside": "Woodside",
    "Yankee Stadium-Macombs Dam Park": "Concourse",
}


def main() -> None:
    with GEO.open(encoding="utf-8") as f:
        geo = json.load(f)
    ntas = sorted(
        {str(ft["properties"]["NTAName"]) for ft in geo["features"] if ft.get("properties", {}).get("NTAName")}
    )
    missing = [n for n in ntas if n not in NTA_MAP]
    extra = [n for n in NTA_MAP if n not in set(ntas)]
    if missing:
        raise SystemExit(f"Missing NTA keys ({len(missing)}): {missing[:20]}...")
    if extra:
        raise SystemExit(f"Extra NTA keys not in GeoJSON ({len(extra)}): {extra[:20]}...")
    for nta, canon in NTA_MAP.items():
        if canon not in CANONICAL:
            raise SystemExit(f"Non-canonical target for {nta!r}: {canon!r}")
    OUT.write_text(json.dumps(NTA_MAP, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(NTA_MAP)} mappings)")


if __name__ == "__main__":
    main()
